{% set version = "2.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tangles
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tangles_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tangles/tangles_{{ version }}.tar.gz
  sha256: 7ee227d1f1d687483abbbb135155c2b1c351cfd8d176e42a9c51b0f36abba16a

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-digest
    - r-sf
    - r-terra
  run:
    - r-base
    - r-digest
    - r-sf
    - r-terra

test:
  commands:
    - $R -e "library('tangles')"           # [not win]
    - "\"%R%\" -e \"library('tangles')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tangles
  license: GPL-2.0-only
  summary: Spatial data anonymization preserves confidentiality. Using methods described in Zandbergen (2014) <doi:10.1155/2014/567049>, spatial data anonymization is achieved by dithering original spatial coordinates with combinations of randomized vertical, horizontal and rotational shifts. This can apply to non-grid spatial
    point patterns and raster objects, and the methods preserve the same spatial characteristics and relationships of the original data. Unique hash keying enables data subjected to anonymization sequences to be re-identified where required.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tangles
# Type: Package
# Title: Anonymization of Spatial Point Patterns and Raster Objects
# Version: 0.8.1
# Date: 2019-10-10
# Authors@R: c(person("Brendan", "Malone", email = "brendan.malone@csiro.au", role = c("cre", "aut")))
# Description: Spatial data anonymization preserves confidentiality. Using methods described in Zandbergen (2014) <doi:10.1155/2014/567049>, spatial data anonymization is achieved by dithering original spatial coordinates with combinations of randomized vertical, horizontal and rotational shifts. This can apply to non-grid spatial point patterns and raster objects, and the methods preserve the same spatial characteristics and relationships of the original data. Unique hash keying enables data subjected to anonymization sequences to be re-identified where required.
# Depends: R (>= 3.0.1)
# Imports: raster, digest, sp
# Suggests: rasterVis, rgdal, knitr, rmarkdown
# VignetteBuilder: knitr
# License: GPL-2
# LazyData: no
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-10-10 09:18:20 UTC; mal181
# Author: Brendan Malone [cre, aut]
# Maintainer: Brendan Malone <brendan.malone@csiro.au>
# Repository: CRAN
# Date/Publication: 2019-10-11 11:30:02 UTC
